### ISSUE TITLE
Upgrade underscore lib

### ISSUE THREAD

**Issue by aboudreault** [edx-solutions/xblock-mentoring#82]
I've noticed issues when adding a mentoring xblock in the same unit of a adventure xblock (in developmnent). The adventure xblock use underscore 1.4.4, which is the same version than the LMS. It would make sense to upgrade the old mentoring underscore lib (1.3.x)

**Comment by bradenmacdonald** [comment]
We don't use this repo at all anymore, so this is safe to close. Everyone is using the `problem-builder` repo now.
